version: '3'

services:

  db:
    image: postgres:alpine
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=123456

  auth:
    depends_on:
    - db
    image: budgetkey/auth
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/postgres
      EXTERNAL_ADDRESS: localhost:8001

  traefik:
    image: traefik
    command:
    - "--configFile=/etc-traefik/traefik.toml"
    ports:
    - "8001:443"
    volumes:
    - "./traefik.toml:/etc-traefik/traefik.toml"
    - "./traefik.crt:/etc-traefik/traefik.crt"
    - "./traefik.key:/etc-traefik/traefik.key"
